"""Typed data model: schema v0.3 + the additive v0.4 deltas (Pydantic v2)."""

from __future__ import annotations

from .arrangement import (
    ArrangementMeta,
    ArrangementPhase,
    ArrangementRole,
    CompetenceAnchor,
    Lernarrangement,
    SharedProduct,
)
from .assets import (
    Asset,
    AssetLane,
    AssetProvenance,
    ImageLintFinding,
    ImageLintReport,
    IntentionallyFlawed,
    MediaPolicy,
)
from .datasets import DataRef, Dataset, SourceRef
from .texts import AnnotatedText, Annotation, TextSourceRef
from .image_sources import (
    ImageAnnotation,
    ImageSource,
    ImageSourceRef,
    ReproductionRights,
    WorkRights,
)
from .blocks import (
    Block,
    BlockBase,
    ContentFlags,
    InfoBlock,
    RubricCriterion,
    Serves,
    SolutionStep,
    TaskBlock,
    TaskPayload,
)
from .competence import (
    CompetenceDimension,
    DimensionRef,
    SubjectCompetenceModel,
    SubjectCompetenceModelRef,
    printable_coverage,
)
from .derived import (
    CompetenceCoverage,
    DepthProfile,
    DepthTarget,
    Nachweis,
)
from .enums import (
    AnchorMode,
    CognitiveLevel,
    CoreTaskKind,
    CoverageRelation,
    InfoKind,
    Medium,
    Modality,
    Role,
    Stufe,
)
from .provenance import BlockProvenance, ProvenanceSource
from .response import ResponseSpec
from .richtext import InlineRun, RichText, plain_text, to_runs
from .verification import Thread, ThreadRack, VerificationItem
from .worksheet import (
    Baustein,
    Bundle,
    BundleRequest,
    FassungRef,
    LehrplanResolution,
    ResolvedCompetence,
    WorksheetContent,
    WorksheetMeta,
)

__all__ = [
    "Lernarrangement",
    "ArrangementMeta",
    "ArrangementRole",
    "ArrangementPhase",
    "SharedProduct",
    "CompetenceAnchor",
    "Asset",
    "AssetLane",
    "AssetProvenance",
    "ImageLintFinding",
    "ImageLintReport",
    "IntentionallyFlawed",
    "MediaPolicy",
    "DataRef",
    "Dataset",
    "SourceRef",
    "AnnotatedText",
    "Annotation",
    "TextSourceRef",
    "ImageAnnotation",
    "ImageSource",
    "ImageSourceRef",
    "ReproductionRights",
    "WorkRights",
    "Block",
    "BlockBase",
    "ContentFlags",
    "InfoBlock",
    "RubricCriterion",
    "Serves",
    "SolutionStep",
    "TaskBlock",
    "TaskPayload",
    "CompetenceDimension",
    "DimensionRef",
    "SubjectCompetenceModel",
    "SubjectCompetenceModelRef",
    "printable_coverage",
    "CompetenceCoverage",
    "DepthProfile",
    "DepthTarget",
    "Nachweis",
    "CognitiveLevel",
    "AnchorMode",
    "CoreTaskKind",
    "CoverageRelation",
    "InfoKind",
    "Medium",
    "Modality",
    "Role",
    "Stufe",
    "BlockProvenance",
    "ProvenanceSource",
    "ResponseSpec",
    "InlineRun",
    "RichText",
    "plain_text",
    "to_runs",
    "Thread",
    "ThreadRack",
    "VerificationItem",
    "Baustein",
    "Bundle",
    "BundleRequest",
    "FassungRef",
    "LehrplanResolution",
    "ResolvedCompetence",
    "WorksheetContent",
    "WorksheetMeta",
]
