"""Voice reference layer — typed, rights-gated cloning inputs for the audio backend.

The audio analogue of the grounded-facts data layer (`schema/datasets.py`). A
TTS dialogue voice is **selected, never authored**: it clones the timbre of a
real, openly-licensed reference clip drawn from a curated, provenance-stamped
corpus (VCTK/FLEURS, fetched by `tools/fetch_vctk_voices.py`), exactly as a
figure references a `Dataset` by stable id. The reference is the cloning *input*;
the spoken audio is generated by the F5 backend at build time.

Two models, mirroring `SourceRef`/`Dataset`:
* `VoiceSourceRef` — the publisher/licence/attribution citation stamp for the
  corpus the clip came from (the voice analogue of `SourceRef`/`FassungRef`);
  `attribution` is the exact string the licence (e.g. CC BY 4.0) requires.
* `VoiceRef` — the curated in-repo record under `grounding/voices/` (the analogue
  of a `Dataset` entry): who the speaker is (language/gender/age/accent), the
  reference transcript the clip says, and the audio file (re-fetchable, so the
  binary stays git-ignored while the provenance is committed).

Ethics line (enforced by curation, not code): clone consenting, openly-licensed
**young adults**, never minors — even where a CC0 clip of a child exists. That is
the youthful ceiling for a rights-clean path, and matches real exam-audio norms.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class VoiceSourceRef(BaseModel):
    """A citation/licence stamp for an openly-licensed voice corpus (cf. `SourceRef`)."""
    model_config = ConfigDict(extra="forbid")
    publisher: str
    title: str
    url: str | None = None
    corpus_code: str | None = None           # the corpus' stable id (e.g. the HF dataset id)
    licence: str | None = None
    licence_url: str | None = None
    redistributable: bool = False            # may we ship the clip + derived audio? (the rights gate)
    attribution: str                         # the exact citation string the licence requires
    retrieved: str | None = None             # ISO date the fetch tool pulled it


class VoiceRef(BaseModel):
    """A curated, provenance-stamped voice reference — the in-repo record
    (`grounding/voices/<id>.json`), written by a deterministic fetch tool and gated
    by HITL review + the licence gate. The F5 backend clones `audio_file` (saying
    `ref_text`) to voice a dialogue turn whose `(language, persona)` it matches."""
    model_config = ConfigDict(extra="forbid")
    id: str                                  # stable, e.g. "vctk_p225"
    language: str                            # ISO code: en, de, fr, it, es
    gender: str                              # "M" | "F"
    age: int | None = None                   # speaker age (years), when the corpus records it
    accent: str | None = None
    speaker_id: str | None = None            # the corpus' speaker id (re-fetch anchor)
    persona: str | None = None               # casting slot: "youth_m" | "youth_f" | "narrator" | …
    ref_text: str                            # the transcript the reference clip says (F5 ref_text)
    audio_file: str                          # path relative to grounding/voices/ (git-ignored, re-fetchable)
    duration_s: float | None = None
    audio_sha256: str | None = None          # integrity check for the re-fetched binary
    source: VoiceSourceRef
    # --- discovery metadata (curated tags, NOT identity claims) ---
    tags: list[str] = Field(default_factory=list)

    def credit(self) -> str:
        """The attribution line a CC-BY reference must carry through to the product."""
        return self.source.attribution
